import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from "react-native";
import { Ionicons } from "@expo/vector-icons";
import type { ScreenKey } from "../App";
import { AppHeader, Pill, PrimaryButton, ProgressBar, ScreenScroll, SearchField, SectionHeading } from "./components";
import { cases, courses, threads, topics } from "./data";
import { login, register } from "./api";
import { colors } from "./theme";

type NavigateProps = { navigate: (screen: ScreenKey) => void };
type DetailProps = NavigateProps & { goBack: () => void };

export function WelcomeScreen({ navigate }: NavigateProps) {
  return <View style={s.authPage}><View style={s.authMark}><Text style={s.authMarkIcon}>⚖</Text></View><Text style={s.authBrand}>Juris Prudentia</Text><Text style={s.authTagline}>Your law student companion</Text><View style={s.authIllustration}><Text style={s.authIllustrationBook}>▤</Text><Text style={s.authIllustrationScale}>⚖</Text></View><Text style={s.authHeading}>Study law with clarity</Text><Text style={s.authBody}>Organized notes, leading cases, legislation and a trusted student community—all in one place.</Text><View style={s.authActions}><PrimaryButton label="Sign In" onPress={() => navigate("login")} /><PrimaryButton label="Create Student Account" light onPress={() => navigate("register")} /></View></View>;
}

export function LoginScreen({ navigate, goBack }: DetailProps) {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const submit = async () => {
    if (!email.trim() || !password) { Alert.alert("Sign in", "Enter your email and password."); return; }
    setSubmitting(true);
    try { await login(email.trim(), password); navigate("home"); }
    catch (error) { Alert.alert("Sign in failed", error instanceof Error ? error.message : "Please try again."); }
    finally { setSubmitting(false); }
  };
  return <View style={s.flex}><AppHeader title="Welcome back" subtitle="Sign in to continue learning" goBack={goBack} /><ScreenScroll><View style={s.authForm}><Text style={s.authFormIcon}>⚖</Text><Text style={s.authFormTitle}>Sign in</Text><Text style={s.fieldLabel}>EMAIL ADDRESS</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="alex@example.com" placeholderTextColor={colors.muted} style={s.input} /><Text style={s.fieldLabel}>PASSWORD</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="Enter your password" placeholderTextColor={colors.muted} style={s.input} /><TouchableOpacity><Text style={s.forgot}>Forgot password?</Text></TouchableOpacity><PrimaryButton label={submitting ? "Signing in…" : "Sign In"} onPress={submit} /><View style={s.authDivider}><View /><Text>OR</Text><View /></View><PrimaryButton label="Continue with University Account" light /><Text style={s.authSwitch}>New to Juris Prudentia? <Text onPress={() => navigate("register")}>Create account</Text></Text></View></ScreenScroll></View>;
}

export function RegisterScreen({ navigate, goBack }: DetailProps) {
  const [fullName, setFullName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const submit = async () => {
    if (!fullName.trim() || !email.trim() || password.length < 8) { Alert.alert("Create account", "Enter your name, email and a password of at least 8 characters."); return; }
    setSubmitting(true);
    try { await register(fullName.trim(), email.trim(), password); navigate("onboarding"); }
    catch (error) { Alert.alert("Could not create account", error instanceof Error ? error.message : "Please try again."); }
    finally { setSubmitting(false); }
  };
  return <View style={s.flex}><AppHeader title="Create your account" subtitle="Begin your legal studies journey" goBack={goBack} /><ScreenScroll><View style={s.authForm}><Text style={s.fieldLabel}>FULL NAME</Text><TextInput value={fullName} onChangeText={setFullName} placeholder="Your full name" placeholderTextColor={colors.muted} style={s.input} /><Text style={s.fieldLabel}>EMAIL ADDRESS</Text><TextInput value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="student@university.ac.ug" placeholderTextColor={colors.muted} style={s.input} /><Text style={s.fieldLabel}>UNIVERSITY</Text><View style={s.select}><Text style={s.selectText}>Select your university</Text><Text style={s.arrow}>⌄</Text></View><Text style={s.fieldLabel}>PASSWORD</Text><TextInput value={password} onChangeText={setPassword} secureTextEntry placeholder="At least 8 characters" placeholderTextColor={colors.muted} style={s.input} /><View style={s.consent}><View style={s.checkbox} /><Text style={s.consentText}>I agree to the Terms of Use, Privacy Policy and Community Guidelines.</Text></View><PrimaryButton label={submitting ? "Creating account…" : "Create Account"} onPress={submit} /><Text style={s.authSwitch}>Already have an account? <Text onPress={() => navigate("login")}>Sign in</Text></Text></View></ScreenScroll></View>;
}

export function OnboardingScreen({ navigate }: NavigateProps) {
  const [year, setYear] = useState(2);
  return <View style={s.flex}><View style={s.onboardHero}><Text style={s.authMarkIcon}>⚖</Text><Text style={s.onboardStep}>STEP 2 OF 3</Text><Text style={s.onboardTitle}>Set up your study hub</Text><Text style={s.onboardBody}>We’ll use this to organize the right courses and material for you.</Text></View><ScreenScroll><Text style={s.fieldLabel}>PROGRAMME</Text><View style={s.select}><Text style={s.selectText}>Bachelor of Laws</Text><Text style={s.arrow}>⌄</Text></View><Text style={s.fieldLabel}>CURRENT YEAR OF STUDY</Text><View style={s.yearGrid}>{[1,2,3,4].map((item) => <TouchableOpacity onPress={() => setYear(item)} key={item} style={[s.yearOption,year === item && s.yearOptionActive]}><Text style={[s.yearNumber,year === item && s.yearNumberActive]}>{item}</Text><Text style={[s.yearLabel,year === item && s.yearLabelActive]}>Year {item}</Text></TouchableOpacity>)}</View><Text style={s.fieldLabel}>CURRENT SEMESTER</Text><View style={s.tabs}><View style={[s.tab,s.tabActive]}><Text style={[s.tabText,s.tabTextActive]}>Semester 1</Text></View><View style={s.tab}><Text style={s.tabText}>Semester 2</Text></View></View><View style={s.onboardNote}><Text>✓</Text><Text>We found four courses for Year {year}, Semester 1. You can change these later in your profile.</Text></View><PrimaryButton label="Build My Study Hub" onPress={() => navigate("home")} /></ScreenScroll></View>;
}

export function HomeScreen({ navigate }: NavigateProps) {
  return <View style={s.flex}>
    <View style={s.homeHero}>
      <AppHeader onNotifications={() => navigate("notifications")} />
      <TouchableOpacity onPress={() => navigate("search")}><SearchField onFocus={() => navigate("search")} /></TouchableOpacity>
      <View style={s.welcomeRow}><View><Text style={s.welcome}>Welcome back, Alex</Text><Text style={s.heroMuted}>Year 2 · Semester 1</Text></View><Text style={s.heroScale}>⚖</Text></View>
    </View>
    <ScreenScroll>
      <SectionHeading title="Your Study Hub" action="View library" onPress={() => navigate("library")} />
      <View style={s.courseGrid}>{courses.map((course) => <TouchableOpacity onPress={() => navigate("course")} style={s.courseCard} key={course.id}><Text style={s.courseCode}>{course.code}</Text><Text style={s.courseTitle}>{course.title}</Text><Text style={s.mutedSmall}>{course.topics} topics</Text><ProgressBar value={course.progress} /><View style={s.cardFooter}><Text style={s.progressText}>{course.progress}% complete</Text><Text style={s.arrow}>›</Text></View></TouchableOpacity>)}</View>
      <SectionHeading title="Continue Learning" />
      <TouchableOpacity onPress={() => navigate("topic")} style={s.continueCard}><View style={s.iconTile}><Text style={s.iconTileText}>§</Text></View><View style={s.grow}><Text style={s.overline}>CRIMINAL LAW I</Text><Text style={s.cardTitle}>Elements of a Crime</Text><Text style={s.mutedSmall}>Continue from Mens Rea</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>
      <SectionHeading title="Legal Updates" action="See all" />
      {["Supreme Court clarifies the burden of proof", "Electronic evidence guidelines issued"].map((title, i) => <View style={s.newsCard} key={title}><View style={s.newsArt}><Text style={s.newsArtText}>{i ? "§" : "⚖"}</Text></View><View style={s.grow}><Pill>{i ? "PRACTICE DIRECTION" : "JUDICIARY"}</Pill><Text style={s.newsTitle}>{title}</Text><Text style={s.mutedSmall}>{i ? "6" : "4"} min read · Today</Text></View></View>)}
    </ScreenScroll>
  </View>;
}

export function LibraryScreen({ navigate }: NavigateProps) {
  const [tab, setTab] = useState("Courses");
  return <View style={s.flex}><AppHeader title="My Library" onSearch={() => navigate("search")} onNotifications={() => navigate("notifications")} /><ScreenScroll>
    <SearchField placeholder="Search your library…" onFocus={() => navigate("search")} />
    <View style={s.tabs}>{["Courses", "Saved", "Downloads"].map((item) => <TouchableOpacity onPress={() => setTab(item)} key={item} style={[s.tab, tab === item && s.tabActive]}><Text style={[s.tabText, tab === item && s.tabTextActive]}>{item}</Text></TouchableOpacity>)}</View>
    {tab === "Courses" ? <>{[1,2,3].map((year) => <View key={year}><SectionHeading title={`Year ${year}`} />{courses.filter((_c, index) => year === 2 || index < 2).slice(0, year === 2 ? 4 : 2).map((course) => <TouchableOpacity onPress={() => navigate("course")} style={s.listCard} key={`${year}-${course.id}`}><View style={s.courseMonogram}><Text style={s.courseMonogramText}>{course.title.charAt(0)}</Text></View><View style={s.grow}><Text style={s.courseCode}>{course.code} · SEMESTER 1</Text><Text style={s.cardTitle}>{course.title}</Text><ProgressBar value={course.progress} /><Text style={s.progressText}>{course.progress}% complete</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>)}</View>)}</> : <View style={s.emptyState}><Text style={s.emptyIcon}>{tab === "Saved" ? "♡" : "⇩"}</Text><Text style={s.emptyTitle}>{tab === "Saved" ? "No saved materials yet" : "No offline downloads"}</Text><Text style={s.emptyBody}>{tab === "Saved" ? "Save cases and notes to find them quickly here." : "Download notes to study when you are offline."}</Text></View>}
  </ScreenScroll></View>;
}

export function CourseScreen({ navigate, goBack }: DetailProps) {
  const [tab, setTab] = useState("Notes");
  return <View style={s.flex}><AppHeader title="Criminal Law I" subtitle="LAW 2101 · Year 2, Semester 1" goBack={goBack} onSearch={() => navigate("search")} /><View style={s.courseTabs}>{["Notes", "Cases", "Law", "Discuss"].map((item) => <TouchableOpacity onPress={() => setTab(item)} key={item} style={[s.courseTab, tab === item && s.courseTabActive]}><Text style={[s.courseTabText, tab === item && s.courseTabTextActive]}>{item}</Text></TouchableOpacity>)}</View><ScreenScroll>
    {tab === "Notes" && <>{<View style={s.courseSummary}><View><Text style={s.overline}>COURSE PROGRESS</Text><Text style={s.summaryNumber}>86%</Text></View><View style={s.grow}><ProgressBar value={86} /><Text style={s.mutedSmall}>3 of 7 topics completed</Text></View></View>}{topics.map((topic) => <TouchableOpacity onPress={() => navigate("topic")} key={topic.number} style={s.topicCard}><Text style={s.topicIcon}>{topic.icon}</Text><View style={s.grow}><Text style={s.topicTitle}>{topic.number}. {topic.title}</Text><ProgressBar value={topic.progress} color={topic.progress === 100 ? colors.success : colors.gold} /><Text style={s.progressText}>{topic.progress}% complete</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>)}</>}
    {tab === "Cases" && <><SectionHeading title="Leading Cases" action="Open explorer" onPress={() => navigate("cases")} />{cases.slice(0,4).map((item) => <CaseRow key={item.id} item={item} onPress={() => navigate("caseDetail")} />)}</>}
    {tab === "Law" && <>{["The Constitution of Uganda, 1995", "Penal Code Act", "Trial on Indictments Act", "Magistrates Courts Act"].map((law, index) => <View style={s.listCard} key={law}><View style={s.iconTile}><Text style={s.iconTileText}>§</Text></View><View style={s.grow}><Text style={s.cardTitle}>{law}</Text><Text style={s.mutedSmall}>{index === 0 ? "Constitutional framework" : "Relevant provisions and sections"}</Text></View><Text style={s.arrow}>›</Text></View>)}</>}
    {tab === "Discuss" && <><View style={s.callout}><Text style={s.calloutTitle}>Ask your course community</Text><Text style={s.calloutBody}>Discuss difficult principles with classmates and verified moderators.</Text><PrimaryButton label="Open Criminal Law Forum" onPress={() => navigate("community")} /></View>{threads.slice(0,2).map((thread) => <ThreadRow key={thread.title} thread={thread} onPress={() => navigate("thread")} />)}</>}
  </ScreenScroll></View>;
}

export function TopicScreen({ navigate, goBack }: DetailProps) {
  const [section, setSection] = useState("Notes");
  return <View style={s.flex}><AppHeader title="Elements of a Crime" subtitle="Criminal Law I · Topic 2" goBack={goBack} /><View style={s.courseTabs}>{["Notes", "Cases", "Quiz"].map((item) => <TouchableOpacity onPress={() => setSection(item)} key={item} style={[s.courseTab, section === item && s.courseTabActive]}><Text style={[s.courseTabText, section === item && s.courseTabTextActive]}>{item}</Text></TouchableOpacity>)}</View><ScreenScroll>
    {section === "Notes" && <><View style={s.readingMeta}><Pill tone="green">75% COMPLETE</Pill><Text style={s.mutedSmall}>18 min remaining</Text></View><Text style={s.articleHeading}>Actus Reus</Text><Text style={s.articleText}>Actus reus is the external element of an offence. It may consist of a voluntary act, an omission where there is a legal duty to act, or a prohibited state of affairs.</Text><View style={s.definition}><Text style={s.definitionLabel}>KEY PRINCIPLE</Text><Text style={s.definitionText}>Criminal liability normally requires conduct that is voluntary and attributable to the accused.</Text></View><Text style={s.articleSubheading}>Voluntary conduct</Text><Text style={s.articleText}>An involuntary movement generally cannot constitute the actus reus. Courts distinguish true automatism from conduct performed with some degree of control.</Text><TouchableOpacity onPress={() => navigate("caseDetail")} style={s.linkedCase}><Text style={s.linkedCaseIcon}>⚖</Text><View style={s.grow}><Text style={s.overline}>LINKED LEADING CASE</Text><Text style={s.cardTitle}>R v Larsonneur [1933]</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity><Text style={s.articleHeading}>Mens Rea</Text><Text style={s.articleText}>Mens rea describes the required mental element. Depending on the offence, this may be intention, recklessness, knowledge, or another specified state of mind.</Text><PrimaryButton label="Mark Topic Complete" /></>}
    {section === "Cases" && cases.slice(0,3).map((item) => <CaseRow key={item.id} item={item} onPress={() => navigate("caseDetail")} />)}
    {section === "Quiz" && <View style={s.quizCard}><Pill>QUESTION 1 OF 5</Pill><Text style={s.quizQuestion}>Which statement best describes subjective recklessness?</Text>{["The accused should have seen the risk", "The accused saw the risk and unreasonably took it", "The risk was obvious to a reasonable person", "The act caused serious harm"].map((answer, i) => <TouchableOpacity style={s.answer} key={answer}><Text style={s.answerLetter}>{String.fromCharCode(65+i)}</Text><Text style={s.answerText}>{answer}</Text></TouchableOpacity>)}<PrimaryButton label="Check Answer" /></View>}
  </ScreenScroll></View>;
}

export function CasesScreen({ navigate, goBack }: DetailProps) {
  const [filter, setFilter] = useState("All");
  return <View style={s.flex}><AppHeader title="Case Explorer" subtitle="Criminal Law I" goBack={goBack} onSearch={() => navigate("search")} /><ScreenScroll background={colors.navy}>
    <SearchField placeholder="Search cases or citations…" />
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filterRow}>{["All", "Actus Reus", "Mens Rea", "Homicide", "Defences"].map((item) => <TouchableOpacity onPress={() => setFilter(item)} key={item} style={[s.filterChip, filter === item && s.filterChipActive]}><Text style={[s.filterText, filter === item && s.filterTextActive]}>{item}</Text></TouchableOpacity>)}</ScrollView>
    {cases.filter((item) => filter === "All" || item.category === filter).map((item) => <TouchableOpacity onPress={() => navigate("caseDetail")} key={item.id} style={s.darkCase}><View style={s.darkCaseIcon}><Text style={s.goldIcon}>⚖</Text></View><View style={s.grow}><Text style={s.darkCaseTitle}>{item.title}</Text><Text style={s.darkCaseCitation}>{item.citation}</Text><Pill>LEADING CASE</Pill></View><Text style={s.goldArrow}>›</Text></TouchableOpacity>)}
  </ScreenScroll></View>;
}

export function CaseDetailScreen({ goBack }: { goBack: () => void }) {
  return <View style={s.flex}><AppHeader title="Case Brief" subtitle="R v Cunningham [1957]" goBack={goBack} /><ScreenScroll><View style={s.caseHero}><Text style={s.caseHeroIcon}>⚖</Text><Pill>LEADING CASE</Pill><Text style={s.caseTitle}>R v Cunningham</Text><Text style={s.caseCitation}>[1957] 2 QB 396 · Court of Appeal</Text><View style={s.caseActions}><PrimaryButton label="Save Case" light /><PrimaryButton label="Share" light /></View></View>{[["Facts","The accused removed a gas meter from a wall to steal its contents. Gas escaped and endangered a neighbouring occupant."],["Legal issue","Whether “maliciously” required foresight of the relevant risk or could be established through an objective standard."],["Decision","The conviction was quashed because the jury had been directed using an objective meaning of malice."],["Principle","A person is reckless when they foresee a risk and nevertheless go on to take it unreasonably."]].map(([title,body]) => <View style={s.briefSection} key={title}><Text style={s.articleSubheading}>{title}</Text><Text style={s.articleText}>{body}</Text></View>)}<View style={s.definition}><Text style={s.definitionLabel}>EXAM TIP</Text><Text style={s.definitionText}>Use Cunningham when distinguishing subjective recklessness from an objective “reasonable person” test.</Text></View></ScreenScroll></View>;
}

export function CommunityScreen({ navigate }: NavigateProps) {
  const [scope, setScope] = useState("My Courses");
  return <View style={s.flex}><AppHeader title="Community" onSearch={() => navigate("search")} onNotifications={() => navigate("notifications")} /><ScreenScroll><View style={s.communityIntro}><Text style={s.communityIcon}>☁</Text><View style={s.grow}><Text style={s.communityTitle}>Learn together</Text><Text style={s.communityBody}>Ask questions and discuss cases respectfully.</Text></View></View><PrimaryButton label="Ask a New Question" onPress={() => navigate("newQuestion")} /><View style={s.tabs}>{["My Courses", "Recent", "Following"].map((item) => <TouchableOpacity onPress={() => setScope(item)} key={item} style={[s.tab, scope === item && s.tabActive]}><Text style={[s.tabText, scope === item && s.tabTextActive]}>{item}</Text></TouchableOpacity>)}</View><SectionHeading title={scope} />{threads.map((thread) => <ThreadRow key={thread.title} thread={thread} onPress={() => navigate("thread")} />)}</ScreenScroll></View>;
}

export function ThreadScreen({ goBack }: { goBack: () => void }) {
  const replies = [
    { name:"Alex Chen", role:"Student", body:"Can someone clarify the difference between direct and oblique intent in murder cases?", mine:true },
    { name:"Maria S.", role:"Moderator", body:"Direct intent means the result is the defendant's aim. Oblique intent may be found where the result was virtually certain and the defendant appreciated that certainty.", mine:false },
    { name:"John D.", role:"Student", body:"Woollin is helpful because the jury may find intention from virtual certainty, but foresight is evidence rather than a separate form of mens rea.", mine:false },
  ];
  return <View style={s.flex}><AppHeader title="Case Discussion" subtitle="Criminal Law Forum" goBack={goBack} /><ScrollView style={s.threadBg} contentContainerStyle={s.threadScroll}>{replies.map((reply, i) => <View key={`${reply.name}-${i}`} style={[s.messageRow, reply.mine && s.messageMineRow]}><View style={s.avatar}><Text style={s.avatarText}>{reply.name.charAt(0)}</Text></View><View style={[s.message, reply.mine && s.messageMine]}><View style={s.messageHeader}><Text style={s.messageName}>{reply.name}</Text>{reply.role === "Moderator" && <Pill>MODERATOR</Pill>}</View><Text style={s.messageBody}>{reply.body}</Text><Text style={s.messageTime}>{i+8}:2{i} AM</Text></View></View>)}</ScrollView><View style={s.composer}><TextInput placeholder="Ask a question or reply…" placeholderTextColor={colors.muted} style={s.composerInput} multiline /><TouchableOpacity style={s.send}><Text style={s.sendText}>›</Text></TouchableOpacity></View></View>;
}

export function NewQuestionScreen({ goBack }: { goBack: () => void }) {
  return <View style={s.flex}><AppHeader title="Ask a Question" subtitle="Community guidelines apply" goBack={goBack} /><ScreenScroll><Text style={s.fieldLabel}>COURSE</Text><View style={s.select}><Text style={s.selectText}>Criminal Law I</Text><Text style={s.arrow}>⌄</Text></View><Text style={s.fieldLabel}>QUESTION TITLE</Text><TextInput placeholder="Be specific and concise" placeholderTextColor={colors.muted} style={s.input} /><Text style={s.fieldLabel}>DETAILS</Text><TextInput placeholder="Explain what you understand and where you are stuck…" placeholderTextColor={colors.muted} style={[s.input,s.textarea]} multiline /><View style={s.guidelines}><Text style={s.guidelineTitle}>Before posting</Text><Text style={s.guideline}>• Search for similar questions first.</Text><Text style={s.guideline}>• Do not share confidential or personal information.</Text><Text style={s.guideline}>• Be respectful and cite authorities where possible.</Text></View><PrimaryButton label="Publish Question" /></ScreenScroll></View>;
}

export function ProgressScreen({ navigate }: NavigateProps) {
  return <View style={s.flex}><AppHeader title="My Progress" onNotifications={() => navigate("notifications")} /><ScreenScroll><View style={s.progressHero}><Text style={s.overlineLight}>SEMESTER PROGRESS</Text><Text style={s.bigPercent}>64%</Text><ProgressBar value={64} color={colors.gold} /><Text style={s.heroMuted}>18 of 28 topics completed</Text></View><View style={s.statsRow}>{[["12","Day streak"],["36h","Study time"],["24","Cases read"]].map(([value,label]) => <View style={s.statCard} key={label}><Text style={s.statValue}>{value}</Text><Text style={s.mutedSmall}>{label}</Text></View>)}</View><SectionHeading title="Course Progress" />{courses.map((course) => <TouchableOpacity onPress={() => navigate("course")} key={course.id} style={s.progressCourse}><View style={s.progressCircle}><Text style={s.progressCircleText}>{course.progress}%</Text></View><View style={s.grow}><Text style={s.cardTitle}>{course.title}</Text><Text style={s.mutedSmall}>{course.current}</Text><ProgressBar value={course.progress} /></View><Text style={s.arrow}>›</Text></TouchableOpacity>)}<SectionHeading title="This Week" /><View style={s.weekCard}>{[45,68,30,80,55,95,65].map((height,index) => <View style={s.day} key={index}><View style={[s.dayBar,{height}]} /><Text style={s.dayLabel}>{["M","T","W","T","F","S","S"][index]}</Text></View>)}</View></ScreenScroll></View>;
}

export function NotificationsScreen({ goBack }: { goBack: () => void }) {
  const items = [
    ["Community reply", "Maria replied to your question about oblique intent.", "5 min", true],
    ["New legal update", "The Supreme Court issued a decision relevant to Evidence Law.", "1 hr", true],
    ["Study reminder", "Continue Topic 2 in Criminal Law I.", "Yesterday", false],
    ["Course updated", "Two cases were added to Constitutional Law.", "2 days", false],
  ] as const;
  return <View style={s.flex}><AppHeader title="Notifications" goBack={goBack} /><ScreenScroll>{items.map(([title,body,time,unread]) => <View style={[s.notification, unread && s.notificationUnread]} key={title}><View style={[s.notificationDot, !unread && s.notificationDotRead]} /><View style={s.grow}><View style={s.rowBetween}><Text style={s.cardTitle}>{title}</Text><Text style={s.mutedSmall}>{time}</Text></View><Text style={s.notificationBody}>{body}</Text></View></View>)}</ScreenScroll></View>;
}

export function SearchScreen({ navigate, goBack }: DetailProps) {
  const [query, setQuery] = useState("");
  return <View style={s.flex}><AppHeader title="Search" goBack={goBack} /><ScreenScroll><SearchField value={query} onChangeText={setQuery} placeholder="Search all learning content…" />{query.length === 0 ? <><SectionHeading title="Popular Searches" />{["Mens rea", "Burden of proof", "R v Woollin", "Penal Code Act"].map((term) => <TouchableOpacity onPress={() => setQuery(term)} style={s.searchSuggestion} key={term}><Ionicons name="search-outline" size={19} color={colors.muted} style={s.searchSuggestionIcon} /><Text style={s.cardTitle}>{term}</Text></TouchableOpacity>)}</> : <><SectionHeading title="Results" /><TouchableOpacity onPress={() => navigate("topic")} style={s.searchResult}><Pill tone="navy">NOTE</Pill><Text style={s.cardTitle}>Actus Reus and Mens Rea</Text><Text style={s.mutedSmall}>Criminal Law I · Topic 2</Text></TouchableOpacity>{cases.slice(1,4).map((item) => <TouchableOpacity onPress={() => navigate("caseDetail")} style={s.searchResult} key={item.id}><Pill>CASE</Pill><Text style={s.cardTitle}>{item.title}</Text><Text style={s.mutedSmall}>{item.citation}</Text></TouchableOpacity>)}</>}</ScreenScroll></View>;
}

export function ProfileScreen() {
  return <View style={s.flex}><AppHeader title="Profile" /><ScreenScroll><View style={s.profileCard}><View style={s.profileAvatar}><Text style={s.profileAvatarText}>AC</Text></View><Text style={s.profileName}>Alex Chen</Text><Text style={s.profileMeta}>Bachelor of Laws · Year 2</Text><Text style={s.profileMeta}>Makerere University</Text><PrimaryButton label="Edit Profile" light /></View><SectionHeading title="Learning Preferences" />{[["◎","Academic programme","Bachelor of Laws"],["▤","Current semester","Year 2 · Semester 1"],["◉","Notifications","Enabled"],["⇩","Offline downloads","4 items"]].map(([icon,label,value]) => <TouchableOpacity key={label} style={s.settingRow}><Text style={s.settingIcon}>{icon}</Text><View style={s.grow}><Text style={s.cardTitle}>{label}</Text><Text style={s.mutedSmall}>{value}</Text></View><Text style={s.arrow}>›</Text></TouchableOpacity>)}<SectionHeading title="Support" />{["Help centre","Community guidelines","Privacy and terms","Sign out"].map((item) => <TouchableOpacity key={item} style={s.simpleRow}><Text style={[s.cardTitle,item === "Sign out" && {color:colors.danger}]}>{item}</Text><Text style={s.arrow}>›</Text></TouchableOpacity>)}</ScreenScroll></View>;
}

function CaseRow({ item, onPress }: { item: typeof cases[number]; onPress: () => void }) { return <TouchableOpacity onPress={onPress} style={s.listCard}><View style={s.iconTile}><Text style={s.iconTileText}>⚖</Text></View><View style={s.grow}><Text style={s.cardTitle}>{item.title}</Text><Text style={s.mutedSmall}>{item.citation}</Text><Pill>LEADING CASE</Pill></View><Text style={s.arrow}>›</Text></TouchableOpacity>; }
function ThreadRow({ thread, onPress }: { thread: typeof threads[number]; onPress: () => void }) { return <TouchableOpacity onPress={onPress} style={s.threadCard}><View style={s.rowBetween}><Pill tone="navy">CRIMINAL LAW</Pill><Text style={s.mutedSmall}>{thread.time}</Text></View><Text style={s.threadTitle}>{thread.title}</Text><Text style={s.threadPreview} numberOfLines={2}>{thread.preview}</Text><Text style={s.threadMeta}>By {thread.author} · {thread.replies} replies</Text></TouchableOpacity>; }

const s = StyleSheet.create({
  flex:{flex:1}, grow:{flex:1},
  authPage:{flex:1,backgroundColor:colors.navy,padding:28,alignItems:"center",justifyContent:"center"},
  authMark:{width:66,height:66,borderRadius:18,backgroundColor:colors.navy2,alignItems:"center",justifyContent:"center",borderWidth:1,borderColor:colors.navy3},
  authMarkIcon:{fontSize:34,color:colors.gold}, authBrand:{fontFamily:"serif",fontSize:30,fontWeight:"800",color:colors.white,marginTop:14},
  authTagline:{fontSize:12,color:"#AEB8C8",marginTop:4}, authIllustration:{height:150,width:220,marginVertical:25,alignItems:"center",justifyContent:"center",position:"relative"},
  authIllustrationBook:{fontSize:96,color:colors.white,opacity:.92}, authIllustrationScale:{position:"absolute",fontSize:48,color:colors.gold,top:22},
  authHeading:{fontFamily:"serif",fontSize:24,fontWeight:"800",color:colors.white}, authBody:{fontSize:13,color:"#AEB8C8",lineHeight:20,textAlign:"center",marginTop:8,maxWidth:330},
  authActions:{width:"100%",gap:10,marginTop:25}, authForm:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:18},
  authFormIcon:{fontSize:33,color:colors.gold,textAlign:"center"}, authFormTitle:{fontFamily:"serif",fontSize:24,fontWeight:"800",color:colors.navy,textAlign:"center",marginTop:5},
  forgot:{fontSize:12,fontWeight:"800",color:"#8A692B",textAlign:"right",marginVertical:13}, authDivider:{flexDirection:"row",alignItems:"center",gap:10,marginVertical:16},
  authSwitch:{fontSize:12,color:colors.muted,textAlign:"center",marginTop:18}, consent:{flexDirection:"row",alignItems:"flex-start",marginVertical:18},
  checkbox:{width:19,height:19,borderRadius:4,borderWidth:1,borderColor:colors.line,marginRight:9}, consentText:{flex:1,fontSize:11,color:colors.muted,lineHeight:17},
  onboardHero:{backgroundColor:colors.navy,padding:24,alignItems:"center"}, onboardStep:{fontSize:9,fontWeight:"900",letterSpacing:1.4,color:colors.gold,marginTop:12},
  onboardTitle:{fontFamily:"serif",fontSize:25,fontWeight:"800",color:colors.white,marginTop:7}, onboardBody:{fontSize:12,color:"#AEB8C8",textAlign:"center",lineHeight:18,marginTop:5},
  yearGrid:{flexDirection:"row",gap:8}, yearOption:{flex:1,borderWidth:1,borderColor:colors.line,backgroundColor:colors.white,borderRadius:9,paddingVertical:12,alignItems:"center"},
  yearOptionActive:{backgroundColor:colors.navy2,borderColor:colors.navy2}, yearNumber:{fontFamily:"serif",fontSize:20,fontWeight:"800",color:colors.ink},
  yearNumberActive:{color:colors.gold}, yearLabel:{fontSize:9,color:colors.muted}, yearLabelActive:{color:colors.white},
  onboardNote:{flexDirection:"row",gap:9,backgroundColor:colors.successSoft,borderRadius:9,padding:13,marginVertical:20},
  homeHero:{backgroundColor:colors.navy,paddingHorizontal:16,paddingBottom:24}, welcomeRow:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:20},
  welcome:{fontFamily:"serif",fontSize:25,fontWeight:"800",color:colors.white}, heroMuted:{color:"#AEB8C8",fontSize:12,marginTop:4}, heroScale:{fontSize:46,color:colors.gold},
  courseGrid:{flexDirection:"row",flexWrap:"wrap",gap:12}, courseCard:{width:"48%",backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:14},
  courseCode:{fontSize:10,fontWeight:"900",color:"#9A7938",letterSpacing:.7}, courseTitle:{fontFamily:"serif",fontSize:16,fontWeight:"800",color:colors.ink,marginTop:5,marginBottom:4},
  mutedSmall:{color:colors.muted,fontSize:11,marginVertical:4}, cardFooter:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:5},
  progressText:{fontSize:10,color:colors.muted,marginTop:5}, arrow:{fontSize:24,color:colors.muted},
  continueCard:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:14,flexDirection:"row",alignItems:"center"},
  iconTile:{width:44,height:44,borderRadius:9,backgroundColor:colors.navy2,alignItems:"center",justifyContent:"center",marginRight:12}, iconTileText:{color:colors.gold,fontSize:21},
  overline:{fontSize:9,fontWeight:"900",letterSpacing:1,color:"#967534"}, cardTitle:{fontSize:14,fontWeight:"800",color:colors.ink,marginVertical:3},
  newsCard:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:12,flexDirection:"row",marginBottom:10},
  newsArt:{width:76,height:78,borderRadius:8,backgroundColor:colors.navy2,alignItems:"center",justifyContent:"center",marginRight:12}, newsArtText:{fontSize:30,color:colors.gold},
  newsTitle:{fontFamily:"serif",fontSize:15,fontWeight:"800",color:colors.ink,marginTop:7}, tabs:{flexDirection:"row",backgroundColor:"#E9EDF3",borderRadius:9,padding:3,marginTop:16},
  tab:{flex:1,alignItems:"center",paddingVertical:9,borderRadius:7}, tabActive:{backgroundColor:colors.white}, tabText:{fontSize:12,color:colors.muted,fontWeight:"700"}, tabTextActive:{color:colors.navy},
  listCard:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:11,padding:13,flexDirection:"row",alignItems:"center",marginBottom:9},
  courseMonogram:{width:45,height:45,borderRadius:23,backgroundColor:colors.goldSoft,alignItems:"center",justifyContent:"center",marginRight:12}, courseMonogramText:{fontFamily:"serif",fontSize:20,fontWeight:"800",color:"#8A692B"},
  emptyState:{alignItems:"center",paddingVertical:70}, emptyIcon:{fontSize:44,color:colors.gold}, emptyTitle:{fontFamily:"serif",fontSize:19,fontWeight:"800",color:colors.ink,marginTop:12}, emptyBody:{color:colors.muted,textAlign:"center",lineHeight:20,maxWidth:280,marginTop:6},
  courseTabs:{height:47,backgroundColor:colors.navy,flexDirection:"row",paddingHorizontal:10}, courseTab:{flex:1,alignItems:"center",justifyContent:"center",borderBottomWidth:3,borderBottomColor:"transparent"},
  courseTabActive:{borderBottomColor:colors.gold}, courseTabText:{fontSize:11,fontWeight:"800",color:"#9EABBC",textTransform:"uppercase"}, courseTabTextActive:{color:colors.white},
  courseSummary:{backgroundColor:colors.navy2,borderRadius:12,padding:16,flexDirection:"row",alignItems:"center",gap:20,marginBottom:12}, summaryNumber:{fontFamily:"serif",fontSize:30,fontWeight:"800",color:colors.white},
  topicCard:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:10,padding:13,flexDirection:"row",alignItems:"center",marginBottom:9}, topicIcon:{width:31,fontSize:20,color:"#9A7938"}, topicTitle:{fontSize:13,fontWeight:"800",color:colors.ink,marginBottom:8},
  callout:{backgroundColor:colors.goldSoft,borderRadius:12,padding:18,gap:10,marginBottom:16}, calloutTitle:{fontFamily:"serif",fontWeight:"800",fontSize:19,color:colors.navy}, calloutBody:{color:colors.muted,lineHeight:19},
  readingMeta:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:18}, articleHeading:{fontFamily:"serif",fontSize:26,fontWeight:"800",color:colors.navy,marginTop:12,marginBottom:9}, articleSubheading:{fontFamily:"serif",fontSize:19,fontWeight:"800",color:colors.navy,marginBottom:7}, articleText:{fontSize:15,color:"#3E4858",lineHeight:24},
  definition:{backgroundColor:colors.goldSoft,borderLeftWidth:4,borderLeftColor:colors.gold,borderRadius:8,padding:15,marginVertical:18}, definitionLabel:{fontSize:9,fontWeight:"900",color:"#8A692B",letterSpacing:1}, definitionText:{fontFamily:"serif",fontSize:15,fontWeight:"700",lineHeight:22,color:colors.ink,marginTop:6},
  linkedCase:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:10,padding:13,flexDirection:"row",alignItems:"center",marginVertical:16}, linkedCaseIcon:{fontSize:24,color:colors.gold,marginRight:12},
  quizCard:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:17}, quizQuestion:{fontFamily:"serif",fontSize:20,fontWeight:"800",color:colors.ink,lineHeight:27,marginVertical:18},
  answer:{borderWidth:1,borderColor:colors.line,borderRadius:9,padding:12,flexDirection:"row",alignItems:"center",marginBottom:10}, answerLetter:{width:30,height:30,borderRadius:15,backgroundColor:colors.paper,textAlign:"center",paddingTop:6,fontWeight:"900",color:colors.navy,marginRight:10}, answerText:{flex:1,color:colors.ink,lineHeight:19},
  filterRow:{gap:8,paddingVertical:16}, filterChip:{borderWidth:1,borderColor:colors.navy3,borderRadius:17,paddingVertical:8,paddingHorizontal:13}, filterChipActive:{backgroundColor:colors.gold,borderColor:colors.gold}, filterText:{fontSize:11,color:"#AFB9C8",fontWeight:"700"}, filterTextActive:{color:colors.navy},
  darkCase:{backgroundColor:colors.navy2,borderWidth:1,borderColor:colors.navy3,borderRadius:10,padding:13,flexDirection:"row",alignItems:"center",marginBottom:9}, darkCaseIcon:{width:42,height:42,borderRadius:8,backgroundColor:colors.navy,alignItems:"center",justifyContent:"center",marginRight:12}, goldIcon:{fontSize:21,color:colors.gold}, darkCaseTitle:{fontFamily:"serif",fontWeight:"800",fontSize:15,color:colors.white}, darkCaseCitation:{fontSize:11,color:"#AEB8C8",marginVertical:4}, goldArrow:{fontSize:24,color:colors.gold},
  caseHero:{alignItems:"center",backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:20}, caseHeroIcon:{fontSize:38,color:colors.gold,marginBottom:8}, caseTitle:{fontFamily:"serif",fontWeight:"800",fontSize:25,color:colors.navy,marginTop:12}, caseCitation:{color:colors.muted,marginTop:5}, caseActions:{flexDirection:"row",gap:10,marginTop:18}, briefSection:{backgroundColor:colors.white,borderBottomWidth:1,borderBottomColor:colors.line,padding:16},
  communityIntro:{backgroundColor:colors.navy2,borderRadius:12,padding:15,flexDirection:"row",alignItems:"center",marginBottom:12}, communityIcon:{fontSize:32,color:colors.gold,marginRight:14}, communityTitle:{fontFamily:"serif",fontSize:18,fontWeight:"800",color:colors.white}, communityBody:{fontSize:12,color:"#B6C0CF",marginTop:4},
  threadCard:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:11,padding:14,marginBottom:10}, rowBetween:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"}, threadTitle:{fontFamily:"serif",fontWeight:"800",fontSize:16,color:colors.ink,marginTop:10}, threadPreview:{fontSize:12,color:colors.muted,lineHeight:18,marginTop:5}, threadMeta:{fontSize:10,color:"#8C6D30",fontWeight:"700",marginTop:10},
  threadBg:{backgroundColor:colors.navy}, threadScroll:{padding:14,paddingBottom:30}, messageRow:{flexDirection:"row",alignItems:"flex-start",marginBottom:15}, messageMineRow:{flexDirection:"row-reverse"}, avatar:{width:34,height:34,borderRadius:17,backgroundColor:colors.gold,alignItems:"center",justifyContent:"center",marginHorizontal:7}, avatarText:{fontWeight:"900",color:colors.navy}, message:{maxWidth:"78%",backgroundColor:colors.white,borderRadius:12,padding:12}, messageMine:{backgroundColor:colors.goldSoft}, messageHeader:{flexDirection:"row",alignItems:"center",gap:7}, messageName:{fontWeight:"900",fontSize:12,color:colors.ink}, messageBody:{fontSize:13,color:colors.ink,lineHeight:19,marginTop:6}, messageTime:{fontSize:9,color:colors.muted,textAlign:"right",marginTop:7},
  composer:{padding:10,backgroundColor:colors.navy2,flexDirection:"row",alignItems:"flex-end"}, composerInput:{flex:1,minHeight:44,maxHeight:100,backgroundColor:colors.white,borderRadius:10,padding:12,color:colors.ink}, send:{width:44,height:44,borderRadius:9,backgroundColor:colors.gold,alignItems:"center",justifyContent:"center",marginLeft:8}, sendText:{fontSize:28,fontWeight:"900",color:colors.navy},
  fieldLabel:{fontSize:10,fontWeight:"900",letterSpacing:1,color:colors.muted,marginTop:18,marginBottom:7}, select:{height:48,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:9,paddingHorizontal:13,flexDirection:"row",alignItems:"center",justifyContent:"space-between"}, selectText:{color:colors.ink,fontWeight:"700"}, input:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:9,minHeight:48,padding:13,color:colors.ink}, textarea:{height:140,textAlignVertical:"top"},
  guidelines:{backgroundColor:colors.goldSoft,borderRadius:10,padding:15,marginVertical:18}, guidelineTitle:{fontWeight:"900",color:colors.ink,marginBottom:7}, guideline:{fontSize:12,color:colors.muted,lineHeight:20},
  progressHero:{backgroundColor:colors.navy2,borderRadius:12,padding:20}, overlineLight:{fontSize:9,fontWeight:"900",letterSpacing:1,color:colors.gold}, bigPercent:{fontFamily:"serif",fontSize:42,fontWeight:"800",color:colors.white,marginVertical:7}, statsRow:{flexDirection:"row",gap:9,marginTop:12}, statCard:{flex:1,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:10,padding:13,alignItems:"center"}, statValue:{fontFamily:"serif",fontSize:20,fontWeight:"800",color:colors.navy},
  progressCourse:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:11,padding:13,flexDirection:"row",alignItems:"center",gap:12,marginBottom:9}, progressCircle:{width:52,height:52,borderRadius:26,borderWidth:4,borderColor:colors.gold,alignItems:"center",justifyContent:"center"}, progressCircleText:{fontSize:11,fontWeight:"900",color:colors.navy}, weekCard:{height:145,backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:15,flexDirection:"row",alignItems:"flex-end",justifyContent:"space-around"}, day:{alignItems:"center",justifyContent:"flex-end",height:110}, dayBar:{width:18,backgroundColor:colors.gold,borderRadius:5}, dayLabel:{fontSize:10,color:colors.muted,marginTop:7},
  notification:{backgroundColor:colors.white,borderBottomWidth:1,borderBottomColor:colors.line,padding:15,flexDirection:"row",gap:10}, notificationUnread:{backgroundColor:"#FFFDF7"}, notificationDot:{width:8,height:8,borderRadius:4,backgroundColor:colors.gold,marginTop:8}, notificationDotRead:{backgroundColor:colors.line}, notificationBody:{fontSize:12,color:colors.muted,lineHeight:18,marginTop:4},
  searchSuggestion:{flexDirection:"row",alignItems:"center",paddingVertical:14,borderBottomWidth:1,borderBottomColor:colors.line}, searchSuggestionIcon:{marginRight:12}, searchResult:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:10,padding:14,marginBottom:9,alignItems:"flex-start"},
  profileCard:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.line,borderRadius:12,padding:20,alignItems:"center",gap:5}, profileAvatar:{width:78,height:78,borderRadius:39,backgroundColor:colors.navy2,alignItems:"center",justifyContent:"center",borderWidth:3,borderColor:colors.gold}, profileAvatarText:{fontFamily:"serif",fontSize:23,fontWeight:"800",color:colors.white}, profileName:{fontFamily:"serif",fontSize:23,fontWeight:"800",color:colors.navy,marginTop:8}, profileMeta:{fontSize:12,color:colors.muted}, settingRow:{backgroundColor:colors.white,borderBottomWidth:1,borderBottomColor:colors.line,padding:14,flexDirection:"row",alignItems:"center"}, settingIcon:{width:35,fontSize:20,color:colors.gold}, simpleRow:{backgroundColor:colors.white,borderBottomWidth:1,borderBottomColor:colors.line,padding:15,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},
});
