import { AdminShell, Badge, Button, Card, Metric, Progress } from "./components";

export default function Overview() {
  return <AdminShell active="Overview" title="Good evening, Sydney" description="Here is what is happening across the learning platform." action={<Button>＋ Add content</Button>}>
    <div className="metrics"><Metric label="Active students" value="1,248" detail="↑ 8.2% this month" icon="◎" /><Metric label="Published courses" value="18" detail="6 drafts awaiting review" icon="▤" /><Metric label="Cases in library" value="436" detail="21 added this month" icon="⚖" /><Metric label="Open reports" value="7" detail="3 need priority review" icon="!" /></div>
    <div className="grid two"><Card title="Content overview" action={<a>View report →</a>}><div className="progress-item"><div><span>Courses published</span><b>18 / 24</b></div><Progress value={75} /></div><div className="progress-item"><div><span>Cases reviewed</span><b>436 / 510</b></div><Progress value={85} /></div><div className="progress-item"><div><span>Notes published</span><b>92 / 120</b></div><Progress value={77} /></div><div className="progress-item"><div><span>Statutes indexed</span><b>58 / 62</b></div><Progress value={94} /></div></Card><Card title="Items requiring attention" action={<Badge tone="red">7 OPEN</Badge>}><ul className="activity"><li><span className="activity-icon warning">!</span><div><strong>3 community reports</strong><small>Awaiting moderator review</small></div><time>Today</time></li><li><span className="activity-icon">▤</span><div><strong>Evidence Law notes</strong><small>Submitted for approval</small></div><time>2h</time></li><li><span className="activity-icon">◎</span><div><strong>12 student registrations</strong><small>University verification pending</small></div><time>4h</time></li><li><span className="activity-icon">◫</span><div><strong>Judiciary update</strong><small>Scheduled for tomorrow</small></div><time>6h</time></li></ul></Card></div>
    <div className="grid two wide-left"><Card title="Recent content"><table><thead><tr><th>Content</th><th>Type</th><th>Editor</th><th>Status</th></tr></thead><tbody><tr><td><strong>Elements of a Crime</strong><small>Criminal Law I</small></td><td>Topic note</td><td>Maria S.</td><td><Badge tone="green">Published</Badge></td></tr><tr><td><strong>R v Woollin</strong><small>Criminal Law I</small></td><td>Case</td><td>John K.</td><td><Badge tone="gold">Review</Badge></td></tr><tr><td><strong>Electronic Evidence</strong><small>Evidence Law I</small></td><td>News</td><td>Amina N.</td><td><Badge tone="blue">Scheduled</Badge></td></tr></tbody></table></Card><Card title="Platform activity"><div className="chart"><div style={{height:"42%"}} /><div style={{height:"60%"}} /><div style={{height:"48%"}} /><div style={{height:"73%"}} /><div style={{height:"64%"}} /><div style={{height:"88%"}} /><div style={{height:"76%"}} /></div><div className="chart-labels"><span>M</span><span>T</span><span>W</span><span>T</span><span>F</span><span>S</span><span>S</span></div></Card></div>
  </AdminShell>;
}
